### ISSUE TITLE
€

### ISSUE THREAD

**Issue by nclm** [uplaod/FuturaRenner#1]
Hi!
There’s a € in the Light variant, but not in the Regular.
How was the first one drawn? I can imagine it wasn’t from Paul Renner’s original drawings :)

**Comment by noirblancrouge** [comment]
Hi,
Thank's for spotting this!

Actually i don't remember, but I've certainly redraw this one for some personal purpose i think.
I will redraw the € in regular and light, but differently ( based on Caps height ).
